# conf/chunking.yaml
splitter: semantic          # switch from "sliding" to "semantic"
max_tokens: 300             # hard ceiling to prevent jumbo chunks
similarity_threshold: 0.75  # cosine drop that triggers a new chunk
min_tokens: 80              # merge stragglers below this size
overlap_sentences: 2        # no duplicated text → lower token bill
embed_model: text-embedding-3-small
vector_store:
  type: chroma
  path: ./local_chroma
