# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyDatasetType(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DatasetType:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyDatasetType", llm_response=llm_response, mode="request")
        return typing.cast(types.DatasetType, result)

    def ExtractCitation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.CitationEntity"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractCitation", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.CitationEntity"], result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyDatasetType(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DatasetType:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyDatasetType", llm_response=llm_response, mode="stream")
        return typing.cast(types.DatasetType, result)

    def ExtractCitation(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.CitationEntity"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractCitation", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.CitationEntity"], result)

    