###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml-py
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing_extensions import TypeAlias
from typing import Dict, Generic, List, Optional, TypeVar, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class CitationEntity(BaseModel):
    evidence: List[str]
    data_citation: Optional[str] = None
    doc_id: Optional[str] = None
    pages: List[int]

class Document(BaseModel):
    doi: Optional[str] = None
    has_dataset_citation: Optional[bool] = None
    full_text: List[str]
    total_char_length: Optional[int] = None
    parsed_timestamp: Optional[str] = None
    total_tokens: Optional[int] = None
    avg_tokens_per_chunk: Optional[float] = None
    file_hash: Optional[str] = None
    file_path: Optional[str] = None
    n_pages: Optional[int] = None
    citation_entities: Optional[List["CitationEntity"]] = None
