# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class CitationEntity(BaseModel):
    evidence: typing.List[str]
    data_citation: typing.Optional[str] = None
    dataset_type: typing.Optional[types.DatasetType] = None

class DatasetTypeInput(BaseModel):
    citation: typing.Optional["CitationEntity"] = None
    text: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
